version: "3"

services:
  crm-lite:
    container_name: crm-lite
    build: .
    network_mode: host
    volumes:
      - crm-lite-db:/app/database
    restart: unless-stopped
    env_file:
      - .env

volumes:
  crm-lite-db:
    external: true
