version: "3"

services:
  crm-lite:
    container_name: crm-lite
    build: .
    network_mode: host
    volumes:
      - crm-lite-db:/app/data
    restart: unless-stopped
    environment:
      - MAILTRAP_API_TOKEN
      - MAILTRAP_ENDPOINT
      - TO_EMAIL
      - TO_NAME
      - FROM_EMAIL
      - FROM_NAME

volumes:
  crm-lite-db:
    external: true
