version: "3"

services:
  crm-lite:
    container_name: crm-lite
    build: .
    ports:
      - "8080:8080"
    volumes:
      - crm-lite-db:/app/database
    restart: unless-stopped
    env_file:
      - .env

volumes:
  crm-lite-db:
    external: true
